/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-03-17 12:51:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>请填写以下注册信息</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<h1>请填写以下注册信息</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"http://localhost:8080/PIMS/RegisterServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>登录名字:</td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"userName\" size=\"25\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户密码：</td>\r\n");
      out.write("\t<td><input type=\"password\" name=\"password1\" size=\"25\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>重复密码：</td>\r\n");
      out.write("\t<td><input type=\"password\" name=\"password2\" size=\"25\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户姓名：</td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"name\" size=\"25\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户性别：</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<input type=\"radio\" name=\"sex\" value=\"男\" checked=\"checked\">男\r\n");
      out.write("\t<input type=\"radio\" name=\"sex\" value=\"女\">女\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>出生日期：</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<select name=\"year\">\r\n");
      out.write("\t<option value=\"1985\">1985</option>\r\n");
      out.write("\t<option value=\"1986\">1986</option>\r\n");
      out.write("\t<option value=\"1987\">1987</option>\r\n");
      out.write("\t<option value=\"1988\">1988</option>\r\n");
      out.write("\t<option value=\"1989\">1989</option>\r\n");
      out.write("\t<option value=\"1990\">1990</option>\r\n");
      out.write("\t<option value=\"1991\">1991</option>\r\n");
      out.write("\t<option value=\"1992\">1992</option>\r\n");
      out.write("\t<option value=\"1993\">1993</option>\r\n");
      out.write("\t<option value=\"1994\">1994</option>\r\n");
      out.write("\t<option value=\"1995\">1995</option>\r\n");
      out.write("\t</select>年\r\n");
      out.write("\t<select name=\"mouth\">\r\n");
      out.write("\t<option value=\"01\">01</option>\r\n");
      out.write("\t<option value=\"02\">02</option>\r\n");
      out.write("\t<option value=\"03\">03</option>\r\n");
      out.write("\t<option value=\"04\">04</option>\r\n");
      out.write("\t<option value=\"05\">05</option>\r\n");
      out.write("\t<option value=\"06\">06</option>\r\n");
      out.write("\t<option value=\"07\">07</option>\r\n");
      out.write("\t<option value=\"08\">08</option>\r\n");
      out.write("\t<option value=\"09\">09</option>\r\n");
      out.write("\t<option value=\"10\">10</option>\r\n");
      out.write("\t<option value=\"11\">11</option>\r\n");
      out.write("\t<option value=\"12\">12</option>\r\n");
      out.write("\t</select>月\r\n");
      out.write("\t<select name=\"day\">\r\n");
      out.write("\t<option value=\"01\">01</option>\r\n");
      out.write("\t<option value=\"02\">02</option>\r\n");
      out.write("\t<option value=\"03\">03</option>\r\n");
      out.write("\t<option value=\"04\">04</option>\r\n");
      out.write("\t<option value=\"05\">05</option>\r\n");
      out.write("\t<option value=\"06\">06</option>\r\n");
      out.write("\t<option value=\"07\">07</option>\r\n");
      out.write("\t<option value=\"08\">08</option>\r\n");
      out.write("\t<option value=\"09\">09</option>\r\n");
      out.write("\t<option value=\"10\">10</option>\r\n");
      out.write("\t<option value=\"11\">11</option>\r\n");
      out.write("\t<option value=\"12\">12</option>\r\n");
      out.write("\t<option value=\"13\">13</option>\r\n");
      out.write("\t<option value=\"14\">14</option>\r\n");
      out.write("\t<option value=\"15\">15</option>\r\n");
      out.write("\t<option value=\"16\">16</option>\r\n");
      out.write("\t<option value=\"17\">17</option>\r\n");
      out.write("\t<option value=\"18\">18</option>\r\n");
      out.write("\t<option value=\"19\">19</option>\r\n");
      out.write("\t<option value=\"20\">20</option>\r\n");
      out.write("\t<option value=\"21\">21</option>\r\n");
      out.write("\t<option value=\"22\">22</option>\r\n");
      out.write("\t<option value=\"23\">23</option>\r\n");
      out.write("\t<option value=\"24\">24</option>\r\n");
      out.write("\t<option value=\"25\">25</option>\r\n");
      out.write("\t<option value=\"26\">26</option>\r\n");
      out.write("\t<option value=\"27\">27</option>\r\n");
      out.write("\t<option value=\"28\">28</option>\r\n");
      out.write("\t<option value=\"29\">29</option>\r\n");
      out.write("\t<option value=\"30\">30</option>\r\n");
      out.write("\t<option value=\"31\">31</option>\r\n");
      out.write("\t</select>日\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户民族：</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<input type=\"radio\" name=\"nation\" value=\"汉族\" checked=\"checked\">汉族\r\n");
      out.write("\t<input type=\"radio\" name=\"nation\" value=\"其他\">其他\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户学历：</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<select name=\"edu\">\r\n");
      out.write("\t<option value=\"博士\">博士</option>\r\n");
      out.write("\t<option value=\"硕士\">硕士</option>\r\n");
      out.write("\t<option value=\"本科\">本科</option>\r\n");
      out.write("\t<option value=\"专科\">专科</option>\r\n");
      out.write("\t<option value=\"其他\">其他</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户职称：</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<select name=\"work\">\r\n");
      out.write("\t<option value=\"工程师\">工程师</option>\r\n");
      out.write("\t<option value=\"教师\">教师</option>\r\n");
      out.write("\t<option value=\"学生\">学生</option>\r\n");
      out.write("\t<option value=\"职员\">职员</option>\r\n");
      out.write("\t<option value=\"公务员\">公务员</option>\r\n");
      out.write("\t<option value=\"其他\">其他</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>用户电话:</td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"phone\" size=\"25\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>家庭住址：</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<select name=\"place\">\r\n");
      out.write("\t<option value=\"北京\">北京</option>\r\n");
      out.write("\t<option value=\"上海\">上海</option>\r\n");
      out.write("\t<option value=\"广州\">广州</option>\r\n");
      out.write("\t<option value=\"深圳\">深圳</option>\r\n");
      out.write("\t<option value=\"其他\">其他</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>邮箱地址:</td>\r\n");
      out.write("\t<td><input type=\"text\" name=\"email\" size=\"25\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"submit\" value=\"提交\">\r\n");
      out.write("<input type=\"reset\" value=\"重置\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
