/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-03-16 12:39:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lookMessage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lookMessage.LookMessageBean;
import java.util.ArrayList;

public final class updateMessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>修改个人信息</td>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/lookMessage/lookMessage.jsp\">查看个人信息</a></td>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/lookMessage/updatePassword.jsp\">修改密码</a></td>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/main/main.jsp\">返回</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table><hr>\r\n");
      out.write("\r\n");
      out.write("<form action=\"http://localhost:8080/PIMS/UpdateMessageServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"25%\">\r\n");

ArrayList wordlist = (ArrayList)session.getAttribute("wordlist");
if(wordlist == null || wordlist.size() == 0)
{
	response.sendRedirect("http://localhost:8080/PIMS/main/main.jsp");
}
else
{
	for(int i = wordlist.size() - 1; i >= 0; i--)
	{
		LookMessageBean mm = (LookMessageBean)wordlist.get(i);
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>用户姓名</td>\r\n");
      out.write("\t\t<td>");
      out.print(mm.getName() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>用户性别</td>\r\n");
      out.write("\t\t<td>");
      out.print(mm.getSex() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>出生日期</td>\r\n");
      out.write("\t\t<td>");
      out.print(mm.getBirth() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>用户民族</td>\r\n");
      out.write("\t\t<td>");
      out.print(mm.getNation() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>用户学历</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<select name=\"edu\">\r\n");
      out.write("\t\t");
if(mm.getEdu().equals("博士")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"博士\" selected=\"selected\">博士</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"博士\">博士</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getEdu().equals("硕士")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"硕士\" selected=\"selected\">硕士</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"硕士\">硕士</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getEdu().equals("本科")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"本科\" selected=\"selected\">本科</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"本科\">本科</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getEdu().equals("专科")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"专科\" selected=\"selected\">专科</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"专科\">专科</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getEdu().equals("其他")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"其他\" selected=\"selected\">其他</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"其他\">其他</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>用户职称</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<select name=\"work\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getWork().equals("工程师")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"工程师\" selected=\"selected\">工程师</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"工程师\">工程师</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getWork().equals("教师")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"教师\" selected=\"selected\">教师</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"教师\">教师</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getWork().equals("学生")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"学生\" selected=\"selected\">学生</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"学生\">学生</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getWork().equals("职员")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"职员\" selected=\"selected\">职员</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"职员\">职员</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getWork().equals("公务员")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"公务员\" selected=\"selected\">公务员</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"公务员\">公务员</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(mm.getWork().equals("其他")){ 
      out.write("\r\n");
      out.write("\t\t<option value=\"其他\" selected=\"selected\">其他</option>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t<option value=\"其他\">\t其他</option>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>用户电话</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<input type=\"text\" name=\"phone\" value=");
      out.print(mm.getPhone());
      out.write(">\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>家庭住址</td>\r\n");
      out.write("\t\t<td>");
      out.print(mm.getPlace());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>邮箱地址</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<input type=\"text\" name=\"email\" value=");
      out.print(mm.getEmail());
      out.write(">\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");

	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("    <input type=\"submit\" value=\"提交\">\r\n");
      out.write("    <input type=\"reset\" value=\"重置\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
