/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-03-16 12:36:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.friendManager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import friendManager.LookFriendBean;
import java.util.ArrayList;

public final class lookFriend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>个人信息管理系统--查看通讯录</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/friendManager/addFriend.jsp\">增加联系人</a></td>\r\n");
      out.write("<td>查看通讯录</td>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/friendManager/updateFriend.jsp\">修改联系人</a></td>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/friendManager/deleteFriend.jsp\">删除联系人</a></td>\r\n");
      out.write("<td><a href=\"http://localhost:8080/PIMS/main/main.jsp\">返回</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table><hr>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"50%\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>联系人姓名</td>\r\n");
      out.write("<td>电话</td>\r\n");
      out.write("<td>邮箱</td>\r\n");
      out.write("<td>职称</td>\r\n");
      out.write("<td>家庭住址</td>\r\n");
      out.write("<td>QQ</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

ArrayList friendslist = (ArrayList)session.getAttribute("friendslist");
if(friendslist == null || friendslist.size() == 0)
{

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<h1>你还没有任何联系人</h1>\r\n");
      out.write("</div>\r\n");

}
else
{
	for(int i = friendslist.size() - 1; i >= 0; i--)	
	{
		LookFriendBean ff = (LookFriendBean)friendslist.get(i);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(ff.getName() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(ff.getPhone() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(ff.getEmail() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(ff.getWorkplace() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(ff.getPlace() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(ff.getQQ() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
		
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
